### ISSUE TITLE
Latest release is missing many assets

### ISSUE THREAD

**Issue by kevin-wallace-wpro** [soos-io/soos-ci-analysis-python#63]
Title says it all. Thank you!

**Comment by SOOS-JAlvarez** [comment]
Hi, thanks for reporting the issue, now it should be fixed, sorry for the inconvenience.

Let me know if the issue was solved or you have any other questions otherwise im going to close the issue in a couple days.

**Comment by kevin-wallace-wpro** [comment]
Looks good, ty
